import type { SeedQuestion, SeedRubric, SeedTopic, SeedTrack } from "@readi/shared-types";
import type { LoadedSeedFile } from "./seed-loader";

/**
 * One printable page per role, built from the seed files, for the experts who review drafted
 * content (CLAUDE.md §7.7). Reading YAML is a skill; reading a question next to its rubric is the
 * job. The document puts each question, its answer key and its five level descriptors together,
 * with a tick-box list of the five things a reviewer is being asked, and the drafter's own
 * uncertainties spelled out.
 */

export interface ReviewDoc {
  role: string;
  markdown: string;
}

const LEVEL_NAMES = ["absent", "weak", "partial", "solid", "excellent"] as const;

export function buildReviewDoc(
  role: string,
  files: readonly LoadedSeedFile[],
  options: { generatedBy: string },
): ReviewDoc {
  const rubrics = new Map<string, SeedRubric>();
  const topics = new Map<string, SeedTopic>();
  /** Role names come from `roles.yaml` now, not a map in this file (ADR-0015). */
  const roleNames = new Map<string, string>();
  const questions: SeedQuestion[] = [];
  let track: SeedTrack | undefined;
  let author = "ai_draft";

  for (const { data } of files) {
    for (const rubric of data.rubrics ?? []) rubrics.set(rubric.slug, rubric);
    for (const topic of data.topics ?? []) topics.set(topic.slug, topic);
    for (const role of data.career_roles ?? []) roleNames.set(role.slug, role.name);
  }
  for (const { file, data } of files) {
    if (!inRole(file, role)) continue;
    questions.push(...(data.questions ?? []));
    if (data.track) track = data.track;
    author = data.author;
  }

  const lessons = (track?.modules ?? []).flatMap((module) => module.lessons);
  const out: string[] = [];

  out.push(`# ${roleNames.get(role) ?? role} — drafted content for expert review`);
  out.push("");
  out.push(
    `**${questions.length} questions**, ${rubricsUsedBy(questions, rubrics).size} rubrics, ` +
      `${track ? `1 track (${track.modules.length} modules, ${lessons.length} lessons)` : "no track"}.`,
  );
  out.push("");
  out.push(
    `Everything here is a **draft written by \`${author}\`** and is invisible to candidates until ` +
      "a human publishes it. Your review is what decides whether it ever is.",
  );
  out.push("");
  out.push("## What we are asking you");
  out.push("");
  out.push(
    "For each question, five questions — the tick boxes under each one are there to be ticked:",
  );
  out.push("");
  out.push(
    "1. **Would a real interviewer ask this, at this level?** Not " +
      '"is it a fair question" but "have you heard it, or would you ask it, of someone at this ' +
      'stage?"',
  );
  out.push(
    "2. **Is the rubric what a strong answer actually covers?** The answer key and the criteria are " +
      "what the AI scores against. If something important is missing, that is the most valuable " +
      "correction you can make.",
  );
  out.push(
    "3. **Are the five level descriptors distinguishable?** Two people scoring the same answer " +
      "should land on the same number. If 2 and 3 say the same thing in different words, say so.",
  );
  out.push(
    "4. **Is each planned follow-up what you would actually ask next?** The opening prompt asks " +
      "one thing, like a real interviewer; each remaining criterion carries the probe the AI may " +
      "ask if the answer has not already covered it. A probe that repeats the prompt, or that a " +
      "good first answer would always have pre-empted, is worth saying so.",
  );
  out.push("5. **Is anything factually wrong or out of date?** Tools and versions move.");
  out.push("");
  out.push(
    "Mark up this page, or edit the YAML directly — `content/seed/" +
      role +
      "/` — and tell us " +
      "which. Anything you are unsure about is worth writing down; so is anything you would cut.",
  );
  out.push("");
  out.push(
    `_Generated from the seed files by \`${options.generatedBy}\`. Do not edit this file: edit the ` +
      "YAML and regenerate._",
  );

  out.push("", "---", "", "## Questions", "");
  questions.forEach((question, index) => {
    out.push(...renderQuestion(question, index + 1, rubrics, topics));
  });

  if (track) out.push(...renderTrack(track, topics));

  return { role, markdown: `${out.join("\n").trimEnd()}\n` };
}

function renderQuestion(
  question: SeedQuestion,
  number: number,
  rubrics: Map<string, SeedRubric>,
  topics: Map<string, SeedTopic>,
): string[] {
  const out: string[] = [];
  const topic = topics.get(question.topic);
  out.push(`### ${number}. ${question.slug}`);
  out.push("");
  out.push(
    `**${question.type.replace("_", " ")}** · difficulty ${question.difficulty}/5 · ` +
      // Roles, although the page is a role's page: a question usually belongs to more than one,
      // and REVIEW.md asks the reviewer whether each of these is right — which they cannot answer
      // without seeing the ones it already has (ADR-0015).
      `roles: ${question.roles.join(", ")} · ` +
      `${question.levels.join(", ")} · topic: ${topic?.name ?? question.topic}` +
      (question.subtopic ? ` (${question.subtopic})` : "") +
      // Named only when there are any: "stacks: —" on twelve of fourteen questions would be
      // noise, and the absence is the ordinary case (ADR-0015).
      (question.stacks.length > 0 ? ` · stacks: ${question.stacks.join(", ")}` : ""),
  );
  out.push("");
  out.push("**The interviewer asks**");
  out.push("");
  out.push(quote(question.prompt));
  if (question.context) {
    out.push("");
    out.push("**Setup the candidate is given**");
    out.push("");
    out.push(quote(question.context));
  }
  out.push("");
  out.push("**What a strong answer covers** — the answer key; never shown to a candidate");
  out.push("");
  for (const point of question.ideal_points) out.push(`- ${point}`);

  const rubric = rubrics.get(question.rubric);
  out.push("");
  if (!rubric) {
    out.push(`**Rubric \`${question.rubric}\` is missing from the seed files.**`);
  } else {
    out.push(`**Rubric: ${rubric.name}** (\`${rubric.slug}\`)`);
    /*
     * The planned follow-up sits with the criterion it probes rather than in a list of its own,
     * because the question a reviewer is being asked is "does this probe draw out *that*
     * criterion" — which cannot be answered without the criterion beside it. Each criterion
     * therefore says either which probe covers it or that the opening prompt is what asks for it.
     */
    /*
     * Grouped, not keyed: a criterion may carry two probes since 2026-09-23, and a Map of
     * criterion → probe silently showed the reviewer only the second of them. They are printed in
     * the order the question lists them, which is the order the engine reaches for them.
     */
    const probes = new Map<number, string[]>();
    for (const plan of question.planned_follow_ups) {
      probes.set(plan.criterion, [...(probes.get(plan.criterion) ?? []), plan.probe]);
    }
    for (const [position, criterion] of rubric.criteria.entries()) {
      out.push("");
      out.push(`**${criterion.dimension} — ${criterion.weight}%**`);
      out.push("");
      out.push(criterion.description);
      out.push("");
      for (const [band, name] of LEVEL_NAMES.entries()) {
        out.push(`- **${band} (${name}):** ${criterion.levels[String(band) as "0"]}`);
      }
      const planned = probes.get(position) ?? [];
      out.push("");
      if (planned.length > 0) {
        out.push(
          planned.length === 1
            ? "_Planned follow-up — asked only if the answer has not already covered this:_"
            : "_Planned follow-ups — asked only if the answer has not already covered this, and the " +
                "second only if the first did not draw it out:_",
        );
        for (const probe of planned) {
          out.push("");
          out.push(quote(probe));
        }
      } else {
        out.push("_Asked for by the opening prompt; no planned follow-up._");
      }
    }
  }

  out.push("");
  out.push(`> **The drafter is unsure about:** ${question.reviewer_notes}`);
  out.push("");
  out.push("- [ ] a real interviewer would ask this, at this level");
  out.push("- [ ] the rubric is what a strong answer actually covers");
  out.push("- [ ] the five level descriptors are distinguishable");
  out.push("- [ ] each planned follow-up is what you would actually ask next");
  out.push("- [ ] nothing here is wrong or out of date");
  out.push("");
  out.push("---");
  out.push("");
  return out;
}

function renderTrack(track: SeedTrack, topics: Map<string, SeedTopic>): string[] {
  const out: string[] = [];
  out.push(`## Track: ${track.title}`);
  out.push("");
  out.push(`\`${track.slug}\` · ${track.role} · ${track.level}`);
  if (track.summary) out.push("", track.summary);
  out.push("");
  out.push(
    "**Topics covered** (core topics drive the readiness score): " +
      track.topics
        .map(
          (link) =>
            `${topics.get(link.topic)?.name ?? link.topic}${link.core ? " **(core)**" : ""}`,
        )
        .join(", "),
  );
  for (const module of track.modules) {
    out.push("", `### ${module.title}`);
    if (module.summary) out.push("", module.summary);
    for (const lesson of module.lessons) {
      out.push("", `#### ${lesson.title}`);
      out.push(
        "",
        `\`${lesson.slug}\`${lesson.estimated_minutes ? ` · ${lesson.estimated_minutes} min` : ""}`,
      );
      out.push("", lesson.body.trim());
    }
    out.push("");
    out.push("- [ ] the lessons above are accurate, current, and worth a junior's time");
  }
  return out;
}

const inRole = (file: string, role: string) => file.split(/[\\/]/).includes(role);

const quote = (text: string) =>
  text
    .split("\n")
    .map((line) => `> ${line}`.trimEnd())
    .join("\n");

function rubricsUsedBy(
  questions: readonly SeedQuestion[],
  rubrics: Map<string, SeedRubric>,
): Set<string> {
  const used = new Set<string>();
  for (const question of questions) if (rubrics.has(question.rubric)) used.add(question.rubric);
  return used;
}
